# Generated by Django 2.0 on 2022-11-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('suela', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('talla', models.IntegerField()),
            ],
        ),
    ]
