# Generated by Django 4.1.1 on 2022-12-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Botas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('suela', models.CharField(choices=[('Cesped Natural', 'Cesped Natural'), ('Cesped Artificial', 'Cesped Artificial'), ('Indoor', 'Indoor')], default='Cesped Natural', max_length=30)),
                ('descripcion', models.TextField(max_length=200)),
                ('gama', models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], default='M', max_length=2)),
                ('marca', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla', models.CharField(choices=[('T38', '38'), ('T39', '39'), ('T40', '40'), ('T41', '41'), ('T42', '42'), ('T43', '43'), ('T44', '44'), ('T45', '45'), ('T46', '46')], default='T42', max_length=3)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre', max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=150)),
                ('formaPago', models.CharField(choices=[('Contrareembolso', 'Contrareembolso'), ('PaaS', 'Paas')], default='Contrareembolso', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BotasCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('bota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.botas')),
            ],
        ),
    ]
