# Generated by Django 2.1.5 on 2022-12-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botas',
            name='agotado',
            field=models.BooleanField(default=False),
        ),
    ]
