# Generated by Django 4.1.1 on 2022-12-05 14:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_atencionc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En almacén', 'En almacén'), ('En reparto', 'En reparto'), ('Entregado', 'Entregado')], default='En almacén', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idSeguimiento',
            field=models.CharField(default=app.models.random_id, editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='botas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
