# Generated by Django 2.0 on 2022-11-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_botas_talla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botas',
            old_name='material',
            new_name='gama',
        ),
        migrations.AddField(
            model_name='botas',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='botas',
            name='talla',
            field=models.PositiveIntegerField(default=43),
        ),
    ]
