# Generated by Django 4.1.1 on 2022-12-05 14:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pedido_estado_pedido_idseguimiento_alter_botas_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='idSeguimiento',
            field=models.CharField(default=app.models.random_id, max_length=5),
        ),
    ]
