# Generated by Django 2.0 on 2022-11-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221122_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botas',
            name='precio',
        ),
    ]
