# Generated by Django 2.0 on 2022-11-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_botas_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='botas',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botas',
            name='talla',
            field=models.PositiveIntegerField(),
        ),
    ]
