# Generated by Django 2.0 on 2022-11-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221122_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='botas',
            name='descripcion',
            field=models.TextField(default='Descripcion', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botas',
            name='imagen',
            field=models.CharField(default='https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b285b4143d6742fbb4dca7fa00dbdc5e_9366/Bota_de_futbol_Copa_Mundial_Negro_015110_01_standard.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
