# Generated by Django 2.1.5 on 2022-11-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20221122_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botas',
            name='gama',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='botas',
            name='suela',
            field=models.CharField(choices=[('CESPEDN', 'Cesped Natural'), ('CESPEDA', 'Cesped Artificial'), ('INDOOR', 'Indoor')], default='CESPEDN', max_length=10),
        ),
        migrations.AlterField(
            model_name='botas',
            name='talla',
            field=models.CharField(choices=[('T38', '38'), ('T39', '39'), ('T40', '40'), ('T41', '41'), ('T42', '42'), ('T43', '43'), ('T44', '44'), ('T45', '45'), ('T46', '46')], default='T42', max_length=3),
        ),
    ]
