# Generated by Django 2.0 on 2022-11-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20221122_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/botas/'),
        ),
    ]
