# Generated by Django 2.0 on 2022-11-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221126_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botas',
            name='gama',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='botas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='botas',
            name='suela',
            field=models.CharField(choices=[('Cesped Natural', 'Cesped Natural'), ('Cesped Artificial', 'Cesped Artificial'), ('Indoor', 'Indoor')], default='Cesped Natural', max_length=30),
        ),
        migrations.AlterField(
            model_name='botas',
            name='talla',
            field=models.CharField(choices=[('T38', '38'), ('T39', '39'), ('T40', '40'), ('T41', '41'), ('T42', '42'), ('T43', '43'), ('T44', '44'), ('T45', '45'), ('T46', '46')], default='T42', max_length=3),
        ),
    ]
