# Generated by Django 4.1.3 on 2022-11-26 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_carrito_alter_botas_id_botascarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='botascarrito',
            name='carrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.carrito'),
            preserve_default=False,
        ),
    ]
