# Generated by Django 2.1.5 on 2022-11-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221127_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botas',
            name='suela',
            field=models.CharField(choices=[('CESPEDN', 'Cesped Natural'), ('CESPEDA', 'Cesped Artificial'), ('INDOOR', 'Indoor')], max_length=10),
        ),
    ]
