# Generated by Django 2.1.5 on 2022-11-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221127_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botas',
            name='suela',
            field=models.CharField(choices=[('Cesped Natural', 'Cesped Natural'), ('Cesped Artificial', 'Cesped Artificial'), ('Indoor', 'Indoor')], default='Cesped Natural', max_length=10),
        ),
    ]
