# Generated by Django 4.1.3 on 2022-11-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_botascarrito_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botascarrito',
            name='carrito',
        ),
    ]
