# Generated by Django 2.0 on 2022-12-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221127_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre', max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('direccion', models.CharField(max_length=150)),
                ('formaPago', models.CharField(choices=[('Contrareembolso', 'Contrareembolso'), ('PaaS', 'Paas')], default='Contrareembolso', max_length=20)),
            ],
        ),
    ]
