# Generated by Django 4.1.1 on 2022-11-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_botas_id'),
        ('app', '0008_auto_20221127_1245'),
    ]

    operations = [
    ]
