# Generated by Django 4.1.3 on 2022-11-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_botascarrito_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='botascarrito',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.carrito'),
        ),
    ]
